import type { Config } from 'tailwindcss'

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        bg: '#FDFBF7',
        canvas: '#F3EFE6',
        text: '#2C241B',
        darkSub: '#5A4F43',
        sub: '#8C7E6A',
        lightSub: '#A69986',
        placeholder: '#C4B8A5',
        border: '#E8E3D9',
        muted: '#F3EFE6',
        accent: '#D4AF37',
        brown: '#C69C6D',
        danger: '#D9734C',
        accentBg: '#FFF9F0',
        kakaoYellow: '#FEE500',
        tagBgFood: '#FFEADD',
        tagBgCafe: '#FFF2D1',
        tagFgCafe: '#B88B2D',
        tagBgPlay: '#EAE4FE',
        tagFgPlay: '#8B6CE0',
        sparkleYellow: '#E9C867',
        sparkleOrange: '#F0A282',
        sparklePurple: '#B994F2',
      },
      borderRadius: {
        compact: '16px',
        card: '20px',
        hero: '28px',
        chip: '9999px',
      },
      backgroundImage: {
        'gold-gradient': 'linear-gradient(to right, #D4AF37, #C69C6D)',
        'medal-gold': 'linear-gradient(to bottom right, #FFE7A2, #FFFBD0)',
        'medal-silver': 'linear-gradient(to right, #F4F4F4, #8E8E8E)',
        'medal-bronze': 'linear-gradient(to bottom, #FFDBA9, #D0701B)',
      },
      spacing: {
        pageH: '24px',
        headerTop: '55px',
        headerHeight: '56px',
        contentTop: '128px',
        bottomSafe: '120px',
      },
      fontFamily: {
        sans: [
          'Pretendard',
          '-apple-system',
          'BlinkMacSystemFont',
          'Segoe UI',
          'Roboto',
          'Helvetica Neue',
          'Apple SD Gothic Neo',
          'sans-serif',
        ],
      },
    },
  },
  plugins: [],
} satisfies Config
